[package]
name = "stravant/geometry"
description = "A geometry module with the getGeometry and blackboxFindClosestMeshEdge functions."
version = "0.1.2"
license = "MIT"
authors = ["Mark Langen <stravant@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# None :)
